/* ============================================================
   PLAN — Marathon Nice→Cannes, 8 novembre 2026
   Données statiques : zones, archétypes de séances, 12 semaines.
   Ce fichier ne bouge pas lors des mises à jour quotidiennes.
   ============================================================ */

window.META = {
  course:      "Marathon des Alpes-Maritimes Nice → Cannes",
  date:        "2026-11-08T08:00:00+01:00",
  debut_bloc:  "2026-08-17",
  objectif:    { plan: "3h45", course: "3h50", allure: "5:20" },
  priorite:    "Ne pas subir les 5 derniers kilomètres",
  athlete:     { age: 46, poids: 77.1, taille: 185, vo2max: 52, fc_repos: 49, fc_max: 185 }
};

/* ---------- ZONES ---------- */
window.ZONES = {
  Z1:{nom:"Endurance fondamentale", allure:"6:00 – 6:30", kmh:"9,2 – 10,0", fc:"124 – 137", c:"#2a9d8f",
      desc:"Échauffement, retour au calme, footings. Conversation entière possible. Ta zone la plus négligée."},
  Z2:{nom:"Endurance active", allure:"5:35 – 6:00", kmh:"10,0 – 10,7", fc:"137 – 151", c:"#0077b6",
      desc:"Le corps des sorties longues. Confortable mais tu sens que tu travailles."},
  Z3:{nom:"Allure marathon", allure:"5:10 – 5:30", kmh:"10,9 – 11,6", fc:"151 – 163", c:"#ffb703",
      desc:"Ton allure du 8 novembre (5:20/km). Les blocs « dont X′ Z3 » servent à l'automatiser."},
  Z4:{nom:"Seuil", allure:"4:35 – 4:55", kmh:"12,2 – 13,1", fc:"163 – 173", c:"#fb8500",
      desc:"Allure semi / 10 km. Soutenable 40-60 min. C'est ce qui élève ton plafond."},
  Z5:{nom:"VMA", allure:"4:00 – 4:15", kmh:"14,1 – 15,0", fc:"173 – 185", c:"#7209b7",
      desc:"Fractions de 30″ à 3′. Effort 9/10. Sur les fractions courtes, fie-toi à l'allure, pas à la FC."}
};

/* ---------- ARCHÉTYPES DE SÉANCES ----------
   Chaque séance référence un archétype qui porte : l'objectif,
   ce qui se passe musculairement, le résultat recherché, et
   l'adaptation selon la forme du jour.                        */
window.ARCHETYPES = {

 vma_court:{ nom:"VMA courte", ico:"⚡", fam:"Qualité",
  but:"Développer ta vitesse maximale aérobie et l'économie de course.",
  muscu:"Les fractions de 30 à 45 s recrutent tes fibres rapides (type II) sans produire assez de lactate pour te détruire. Le muscle apprend à se contracter vite et à se relâcher vite — c'est le relâchement qui économise l'énergie.",
  resultat:"Une foulée plus ample à effort égal. Concrètement : ton allure marathon te coûtera moins cher en oxygène, donc en glycogène.",
  reussite:"Toutes les fractions à la même allure, la dernière aussi propre que la première.",
  avant:"24 h sans séance dure suffisent : les fractions courtes sollicitent le système nerveux, pas les réserves. Peut se placer 2 jours après une sortie longue.",
  apres:"Peu traumatisante. Un footing facile dès le lendemain est possible, et même une séance de qualité 48 h après.",
  forme:{ top:"Ajoute 2 fractions sur la dernière série.",
          normal:"Séance telle quelle.",
          bof:"Une seule série, récupération allongée à 1′.",
          hs:"Remplace par 40′ en Z1. La VMA sur jambes mortes ne sert à rien." }},

 vma_long:{ nom:"VMA longue", ico:"🔥", fam:"Qualité",
  but:"Maintenir le VO2max et apprendre à tenir une allure inconfortable.",
  muscu:"Sur 1 à 3 minutes, tu atteins ton plafond d'oxygène et le lactate s'accumule. Le corps développe sa capacité à recycler ce lactate comme carburant — un mécanisme qui te servira directement au km 35.",
  resultat:"Meilleure tolérance à l'inconfort et plafond aérobie relevé.",
  reussite:"Tenir l'allure sur la dernière fraction sans t'écrouler.",
  avant:"48 h sans intensité. Jambes fraîches obligatoires.",
  apres:"24 h faciles minimum. Pas de sortie longue le lendemain.",
  forme:{ top:"Séance telle quelle, ne surenchéris pas.",
          normal:"Séance telle quelle.",
          bof:"Retire une fraction par série.",
          hs:"Remplace par 40′ en Z1." }},

 cotes:{ nom:"Côtes", ico:"⛰️", fam:"Force",
  but:"Construire la force spécifique du coureur, sans traumatisme.",
  muscu:"En montée, tes quadriceps et fessiers travaillent en concentrique avec un impact au sol réduit — tu gagnes en force sans casser de fibres. C'est le meilleur rapport bénéfice/risque du plan, et un substitut direct au renfo.",
  resultat:"Des jambes qui poussent plus fort à chaque foulée. Effet direct sur la résistance en fin de marathon.",
  reussite:"Même temps d'ascension entre la 1ʳᵉ et la dernière côte.",
  avant:"24 à 48 h. Moins traumatisante que la VMA à plat pour les quadriceps, mais elle <b>charge fortement les mollets et les tendons d'Achille</b>.",
  apres:"24 h faciles. <b>Évite le renfo jambes le lendemain</b> — les mollets ont déjà donné.",
  forme:{ top:"Ajoute 2 côtes.",
          normal:"Séance telle quelle.",
          bof:"Réduis d'un tiers le nombre de côtes.",
          hs:"Footing plat en Z1." },
  lieux:"À Paris : Buttes-Chaumont, Montmartre, butte du Parc de Belleville, ou la montée de la rue Mouffetard.",
  tapis:"Sur tapis : <b>6 à 8 % d'inclinaison à 10-11 km/h</b>. Récupération inclinaison 0 % en marchant ou trottinant. Avantage du tapis ici : la pente est constante, donc chaque répétition est rigoureusement identique — impossible à obtenir dehors." },

 vo2max:{ nom:"VO2max — intervalles longs", ico:"🫀", fam:"Qualité",
  but:"Passer le maximum de temps à ton plafond d'oxygène — le stimulus le plus puissant qui existe pour élever le VO2max.",
  muscu:"Il faut environ 90 secondes pour que ton cœur atteigne son plafond. Sur des fractions de 4 minutes, tu passes donc ~2min30 à 95-100 % de ton VO2max à chaque répétition — c'est le protocole norvégien classique. Le cœur augmente son volume d'éjection et les mitochondries se densifient.",
  resultat:"Un plafond aérobie plus haut. Conséquence directe : ton allure marathon représente un pourcentage plus faible de ton maximum, donc elle coûte moins cher.",
  reussite:"Les 4 répétitions à la même allure. Si la 4ᵉ s'effondre, tu es parti trop vite.",
  avant:"<b>La séance qui exige le plus de fraîcheur.</b> 48 h sans intensité, idéalement après un jour de repos ou un footing très lent. À placer en début de semaine.",
  apres:"24 h de repos ou footing strictement Z1. <b>Jamais de sortie longue le lendemain</b> — tu ne tiendrais pas les blocs à allure marathon.",
  forme:{ top:"Ajoute une 5ᵉ répétition, jamais plus.",
          normal:"Séance telle quelle.",
          bof:"3 répétitions au lieu de 4, récupération à 4′.",
          hs:"Remplace par 40′ en Z1. Le VO2max sur jambes mortes ne produit que de la fatigue." },
  tapis:"Sur tapis : vise <b>14,5 km/h à 1 % d'inclinaison</b>, mais <b>la FC prime sur la vitesse affichée</b> — si tu dépasses 90 % de FCmax (167 bpm) avant la fin d'un palier, n'accélère pas davantage, l'objectif physiologique est déjà atteint. Beaucoup de tapis sont mal calibrés : la FC est le signal fiable, pas le chiffre affiché. Récupération 3 min à 7-8 km/h. Ne tiens jamais la rampe — ça fausse l'effort et la posture." },

 seuil_2000:{ nom:"Seuil — 2000 m répétés", ico:"🎯", fam:"Qualité",
  but:"Élever le seuil lactique en accumulant du volume à allure semi-marathon.",
  muscu:"Chaque 2000 m dure ~9min30 à l'équilibre exact entre production et élimination du lactate. Répété avec une récupération courte, ce format entraîne les transporteurs qui <b>recyclent le lactate comme carburant</b> au lieu de le subir — exactement le mécanisme qui te servira au km 35.",
  resultat:"8 km cumulés à allure semi. C'est le format qui déplace le plus directement un chrono marathon.",
  reussite:"Moins de 5 secondes d'écart entre le premier et le dernier 2000 m.",
  avant:"48 h sans intensité. C'est la séance clé de sa semaine : place-la quand tu es le plus frais, pas en fin de semaine.",
  apres:"24 h très faciles. Le renfo lourd est à éviter le lendemain.",
  forme:{ top:"Séance telle quelle. Ne pars pas plus vite, tu paierais sur le 4ᵉ.",
          normal:"Séance telle quelle.",
          bof:"3 × 2000 m au lieu de 4, même allure.",
          hs:"45′ en Z2. Le seuil fatigué est contre-productif." },
  tapis:"Sur tapis : <b>12,6 km/h (4:45/km) à 1 % d'inclinaison</b>. Récupération 2 min à 7 km/h. Chaque bloc dure 9:30." },

 interval_1000:{ nom:"1000 m répétés", ico:"⏱️", fam:"Qualité",
  but:"Le format polyvalent, à mi-chemin entre VO2max et seuil.",
  muscu:"À allure 10 km, chaque kilomètre dure ~4min35 et te place juste au-dessus du seuil. La récupération courte empêche l'élimination complète du lactate entre les répétitions : tu apprends à courir vite en présence de fatigue accumulée.",
  resultat:"Meilleure résistance à l'acidose, et allure spécifique 10 km affûtée.",
  reussite:"Les 6 kilomètres dans un mouchoir de 5 secondes.",
  avant:"24 à 48 h sans intensité. Moins exigeante que le VO2max, elle tolère d'arriver un peu fatigué.",
  apres:"24 h faciles. Peut être suivie d'une sortie longue 48 h après.",
  forme:{ top:"Ajoute un 7ᵉ kilomètre.",
          normal:"Séance telle quelle.",
          bof:"4 répétitions, récupération à 2′30.",
          hs:"40′ en Z1." },
  tapis:"Sur tapis : <b>13,1 km/h (4:35/km) à 1 % d'inclinaison</b>. Récupération 2 min à 7-8 km/h." },

 off:{ nom:"Coupure", ico:"🥂", fam:"Récupération",
  but:"Assimiler la charge des trois semaines précédentes — et vivre.",
  muscu:"Trois jours sans course après un bloc de charge, c'est une fenêtre de surcompensation : le glycogène se reconstitue totalement, les micro-lésions cicatrisent, le système nerveux se réinitialise. La progression se produit pendant cette phase, pas pendant l'effort.",
  resultat:"Tu reviens plus fort le lundi suivant. À condition de ne pas culpabiliser.",
  reussite:"Ne pas courir. Vraiment pas.",
  avant:"Rien à préparer — c'est planifié.",
  apres:"Reprise progressive : commence par une séance de qualité sur jambes fraîches, c'est le moment idéal.",
  forme:{ top:"Coupure quand même — c'est planifié, pas subi.",
          normal:"Coupure.", bof:"Coupure.", hs:"Coupure, et dors." }},

 seuil:{ nom:"Seuil", ico:"🎯", fam:"Qualité",
  but:"Repousser le seuil au-delà duquel le lactate s'accumule plus vite qu'il n'est éliminé.",
  muscu:"À cette intensité, tu es exactement à l'équilibre entre production et élimination du lactate. En t'entraînant juste à ce point, tu déplaces le curseur : la même allure devient soutenable plus longtemps.",
  resultat:"C'est la séance qui a le plus d'effet direct sur ton chrono marathon. Elle élève le plafond sous lequel se situe ton allure de course.",
  reussite:"Allure régulière du premier au dernier bloc. Si le dernier s'effondre, tu es parti trop vite.",
  avant:"48 h sans intensité.",
  apres:"24 h faciles. Pas de sortie longue le lendemain.",
  forme:{ top:"Séance telle quelle — la tentation d'accélérer est le piège classique.",
          normal:"Séance telle quelle.",
          bof:"Retire un bloc, garde l'allure.",
          hs:"Transforme en 45′ Z2. Le seuil fatigué est contre-productif." }},

 sl:{ nom:"Sortie longue", ico:"🛣️", fam:"Endurance",
  but:"Construire l'endurance musculaire et l'aptitude à brûler les graisses.",
  muscu:"Au-delà de 1h30, tes réserves de glycogène baissent et le corps bascule progressivement sur les lipides. Il densifie aussi tes mitochondries et tes capillaires. En parallèle, tes fibres encaissent des micro-lésions répétées : c'est en les réparant qu'elles deviennent résistantes aux 35 000 impacts du jour J.",
  resultat:"C'est LA séance qui fait le marathon. Ton déficit actuel est là, pas ailleurs.",
  reussite:"Finir en te disant que tu aurais pu continuer 20 minutes.",
  avant:"24 h faciles minimum. <b>Jamais le lendemain d'une séance de seuil ou de VMA.</b>",
  apres:"Lendemain : repos, natation ou vélo souple. Aucune qualité dans les 24 h.",
  forme:{ top:"Reste dans la fourchette haute de durée, jamais au-delà.",
          normal:"Milieu de fourchette.",
          bof:"Fourchette basse, tout en Z1-Z2, supprime les blocs Z3.",
          hs:"Coupe à 1h en Z1. Mieux vaut une sortie longue ratée qu'une blessure." }},

 sl_am:{ nom:"Sortie longue + allure marathon", ico:"🏁", fam:"Endurance",
  but:"Automatiser ton allure de course sur des jambes déjà fatiguées.",
  muscu:"Courir à allure marathon après 1h d'effort reproduit précisément l'état du km 25-30. Tu entraînes ton corps à maintenir une foulée efficace alors que le glycogène baisse — c'est exactement la compétence qui te manque pour les 5 derniers kilomètres.",
  resultat:"L'allure 5:20/km doit devenir un automatisme, pas un effort de concentration.",
  reussite:"Les blocs Z3 tenus sans dérive cardiaque de plus de 5 bpm.",
  avant:"24 h faciles minimum, 48 h après une grosse séance de qualité. <b>Les blocs à allure marathon exigent des jambes correctes</b> : si tu as tapé fort l'avant-veille, supprime-les plutôt que de bâcler la sortie.",
  apres:"Lendemain : repos, natation ou vélo souple. C'est la séance la plus coûteuse du plan, respecte sa récupération.",
  forme:{ top:"Séance telle quelle. Ne dépasse pas l'allure prévue.",
          normal:"Séance telle quelle.",
          bof:"Réduis les blocs Z3 de moitié, garde la durée totale.",
          hs:"Supprime les blocs Z3, fais la sortie en Z2 basse." },
  ravito:"Gel toutes les 35-40 min dès la 8ᵉ km, avec la marque exacte prévue pour le jour J." },

 endurance:{ nom:"Endurance", ico:"🌿", fam:"Foncier",
  but:"Accumuler du volume aérobie sans coût de récupération.",
  muscu:"À cette intensité, tu développes ton réseau capillaire et tes mitochondries sans créer de fatigue nerveuse. Le corps répare pendant que tu cours.",
  resultat:"La base sur laquelle tout le reste repose. Et ta correction n°1 : ces footings doivent être LENTS.",
  reussite:"Rester sous 137 bpm, même si l'allure te semble ridicule.",
  avant:"Aucune contrainte — <b>c'est la séance tampon du plan</b>. Elle sert à combler les trous entre deux séances dures.",
  apres:"Aucune. Elle peut précéder ou suivre n'importe quoi, y compris une sortie longue.",
  forme:{ top:"Tu peux allonger de 10 min, sans accélérer.",
          normal:"Séance telle quelle.",
          bof:"Raccourcis de 15 min, garde l'allure lente.",
          hs:"Repos complet ou 20′ très souple." }},

 acc:{ nom:"Accélérations", ico:"💨", fam:"Technique",
  but:"Travail technique : fréquence, relâchement, amplitude.",
  muscu:"Des lignes droites de ~100 m en progressif — tu montes en vitesse sur 60 m, tu tiens 30 m relâché, tu redescends. L'objectif est nerveux et technique, pas énergétique. Aucune fatigue générée.",
  resultat:"Une foulée plus économique, sans coût de récupération.",
  reussite:"Sensation de facilité, jamais d'essoufflement.",
  avant:"Aucune contrainte. Utilisable même en fin de semaine chargée.",
  apres:"Aucune. Elle ne génère pas de fatigue.",
  forme:{ top:"Séance telle quelle.", normal:"Séance telle quelle.",
          bof:"Réduis de moitié le nombre d'accélérations.", hs:"Supprime les accélérations, footing seul." }},

 course:{ nom:"Course", ico:"🏆", fam:"Compétition",
  but:"Test grandeur nature et validation de l'objectif.",
  muscu:"L'effort maximal en peloton produit une fatigue qu'aucun entraînement ne reproduit : adrénaline, allure imposée, engagement total.",
  resultat:"Un chrono fiable pour calibrer l'allure marathon, et l'habitude des conditions de course.",
  reussite:"Négative split : seconde moitié plus rapide que la première.",
  avant:"<b>3 jours d'allègement minimum.</b> Dernière séance dure 4 à 5 jours avant. La veille : 20-30 min très souple avec quelques accélérations.",
  apres:"Une semaine sans séance de qualité. Compte 1 jour de récupération par tranche de 3 km courus en compétition.",
  forme:{ top:"Vise la fourchette haute de l'objectif.",
          normal:"Objectif prévu.",
          bof:"Pars 10 s/km plus lentement et avise à mi-course.",
          hs:"Cours-la en entraînement, sans chrono. Ta santé passe avant un dossard." }},

 renfo_a:{ nom:"Renfo A — Force", ico:"🏋️", fam:"Renforcement",
  but:"Développer la force maximale des chaînes utilisées en course.",
  muscu:"Charges lourdes, peu de répétitions, descente freinée : tu recrutes un maximum de fibres et tu renforces les tendons. La phase excentrique (freiner la charge) est ce qui protège tes quadriceps de la destruction du marathon.",
  resultat:"Des jambes qui encaissent l'impact au lieu de le subir.",
  reussite:"Dernière répétition difficile mais techniquement propre.",
  avant:"À coupler avec un jour sans course, ou juste après un footing facile. <b>Jamais dans les 48 h avant la sortie longue.</b>",
  apres:"48 h avant toute séance de qualité en course : les courbatures altèrent la foulée et augmentent le risque de blessure.",
  forme:{ top:"Monte de 5-10 kg sur leg press et hip thrust.",
          normal:"Charges de la semaine précédente.",
          bof:"Réduis les charges de 20 %, garde le nombre de séries.",
          hs:"Saute la séance. Le renfo sert la course, pas l'inverse." },
  exercices:[
   {nom:"Leg press",series:4,reps:"12",charge:"210 kg",tempo:"3 s descente"},
   {nom:"Leg curl assis",series:4,reps:"12",charge:"60 kg",tempo:"4 s retour"},
   {nom:"Hip thrust",series:4,reps:"12",charge:"70 kg",tempo:"1 s bloqué en haut"},
   {nom:"Abduction hanche",series:3,reps:"20",charge:"95 kg",tempo:"contrôlé"},
   {nom:"Adduction hanche",series:3,reps:"15",charge:"80 kg",tempo:"contrôlé"},
   {nom:"Mollets assis",series:4,reps:"15",charge:"61 kg",tempo:"3 s descente"},
   {nom:"Back extension",series:3,reps:"15",charge:"10 kg",tempo:"contrôlé"},
   {nom:"Pallof press",series:3,reps:"10/côté",charge:"20 kg poulie",tempo:"2 s tenue"}
  ]},

 renfo_b:{ nom:"Renfo B — Unilatéral", ico:"🦵", fam:"Renforcement",
  but:"Apprendre à ton corps à se stabiliser sur une jambe.",
  muscu:"Un marathon, ce sont ~35 000 appuis unipodaux encaissant chacun 2,5 à 3 fois ton poids. Les machines te stabilisent à ta place — or ce sont précisément les stabilisateurs de hanche qui lâchent en fin de course et font s'effondrer le bassin.",
  resultat:"Le chaînon manquant de ta préparation, et le lien le plus direct avec ton objectif de finir debout.",
  reussite:"Bassin stable, genou qui ne part pas vers l'intérieur.",
  avant:"<b>La plus traumatisante du plan les premières fois.</b> Jamais dans les 48 h avant la sortie longue ni avant une séance de qualité.",
  apres:"Les courbatures d'unilatéral durent 48 h au début. Prévois derrière un footing très facile, de la natation, ou du repos.",
  forme:{ top:"Format complet, haltères.",
          normal:"Format complet.",
          bof:"2 séries au lieu de 3, poids du corps.",
          hs:"Saute la séance." },
  exercices:[
   {nom:"Leg press une jambe",series:3,reps:"10/jambe",charge:"70 kg",tempo:"3 s descente"},
   {nom:"Fentes bulgares",series:3,reps:"8/jambe",charge:"2 × 8 kg",tempo:"descente lente"},
   {nom:"Step-up sur banc",series:3,reps:"10/jambe",charge:"2 × 8 kg",tempo:"descente freinée"},
   {nom:"Glute kickback",series:3,reps:"15/jambe",charge:"27 kg",tempo:"1 s pause"},
   {nom:"Mollets debout, une jambe",series:3,reps:"12/jambe",charge:"poids du corps",tempo:"3 s descente"},
   {nom:"Planche + planche latérale",series:3,reps:"45″ + 30″/côté",charge:"—",tempo:"—"}
  ]},

 natation:{ nom:"Natation", ico:"🏊", fam:"Récupération",
  but:"Volume aérobie et récupération active, sans impact.",
  muscu:"La position horizontale et la pression de l'eau favorisent le retour veineux : tu évacues les déchets métaboliques des jambes plus vite qu'au repos. Zéro impact, donc zéro fatigue supplémentaire.",
  resultat:"Récupération accélérée et entretien du moteur aérobie.",
  reussite:"Sortir de l'eau avec les jambes plus légères qu'en entrant.",
  avant:"Aucune contrainte.",
  apres:"Aucune. <b>Placement idéal : le lendemain de la sortie longue</b>, pour drainer les jambes sans impact.",
  forme:{ top:"2 000 m endurance.", normal:"1 500-2 000 m.",
          bof:"1 500 m récup, éducatifs.", hs:"500 m très souple ou repos." }},

 velo:{ nom:"Vélo / home trainer", ico:"🚴", fam:"Récupération",
  but:"Volume aérobie sans impact, ou pré-fatigue contrôlée.",
  muscu:"Après une sortie longue, le pédalage souple draine les jambes sans ajouter de micro-lésions. En complément d'une SL, il prolonge le temps en déplétion de glycogène — l'état du km 35 — sans le coût articulaire.",
  resultat:"Volume aérobie gratuit, sans facture musculaire.",
  reussite:"Pédalage souple, jamais en force.",
  avant:"Aucune contrainte.",
  apres:"Aucune. Idéal en récupération le lendemain d'un gros effort.",
  forme:{ top:"1h.", normal:"1h.", bof:"40 min très souple.", hs:"Repos." }},

 repos:{ nom:"Repos", ico:"😴", fam:"Récupération",
  but:"C'est pendant le repos que tu progresses, pas pendant l'effort.",
  muscu:"La synthèse protéique et la reconstitution du glycogène se font au repos. Sans ce temps, l'entraînement ne produit que de la fatigue accumulée.",
  resultat:"Assimilation de la charge des jours précédents.",
  reussite:"Ne rien faire, vraiment.",
  avant:"—",
  apres:"—",
  forme:{ top:"Repos quand même.", normal:"Repos.", bof:"Repos.", hs:"Repos + couche-toi tôt." }}
};

/* ---------- LES 12 SEMAINES ----------
   past:1  → séance réalisée, importée de Strava
   a       → archétype
   f       → fourchette de durée [min, max] en minutes (optionnel)  */
window.SEMAINES = [

{n:1, dates:"17 – 23 août", du:"2026-08-17", tag:"Réalisé", type:"past", past:1,
 titre:"Indonésie — Lombok & les Gili",
 prevu:"30′ Z1 + 2×8 Acc · 25′ Z1 + 2×(5×1′ Z5) · 1h05-1h10 Z2 · 10 × côte 1′",
 focus:"Semaine de vacances, allures naturellement lentes (chaleur, humidité). Aucune séance structurée, mais 4 sorties et une régularité maintenue.",
 bilan:"Volume conforme au plan, zéro travail de qualité. Point positif inattendu : la chaleur t'a forcé à courir à <b>6:00/km de moyenne</b> — exactement la Z1 que tu as ensuite perdue en rentrant. C'est ta meilleure semaine d'endurance fondamentale de l'été, et elle était involontaire.",
 s:[{d:"Lun 17/08",past:1,k:"run",t:"Footing 9,7 km",lieu:"Lombok",km:9.7,m:{allure:"5:59/km",temps:"57:53"}},
    {d:"Jeu 20/08",past:1,k:"run",t:"Footing court 5,0 km",lieu:"Gili",km:5.0,m:{allure:"5:59/km",temps:"30:00"}},
    {d:"Ven 21/08",past:1,k:"run",t:"Sortie longue 13,4 km",lieu:"Lombok",km:13.4,m:{allure:"5:47/km",temps:"1h17",fc:138}},
    {d:"Sam 22/08",past:1,k:"run",t:"Footing 7,3 km",lieu:"Ubud, rizières",km:7.3,m:{allure:"6:19/km",temps:"46:02"}}]},

{n:2, dates:"24 – 30 août", du:"2026-08-24", tag:"Réalisé", type:"past", past:1,
 titre:"Luberon — Ansouis",
 prevu:"30′ Z1 + 2×10 Acc · 25′ Z1 + 2×(6×1′ Z5) · 1h10-1h15 Z2 · 12 × côte 1′",
 focus:"Ta plus grosse semaine de l'été : 56 km et 740 m de dénivelé en 5 sorties. Le relief a joué le rôle des séances de côtes du plan.",
 bilan:"Excellente semaine, la preuve que tu encaisses le volume. Nuance : toutes tes sorties sont entre 5:21 et 5:56/km — <b>tu n'as jamais vraiment couru lentement, ni vraiment vite</b>. C'est la zone grise que le bloc va casser.",
 s:[{d:"Lun 24/08",past:1,k:"run",t:"Sortie longue vallonnée 13,8 km",lieu:"D+ 203 m · 5K en 25:45",km:13.8,m:{allure:"5:39/km",temps:"1h18",fc:144}},
    {d:"Mar 25/08",past:1,k:"run",t:"Footing soutenu 10,2 km",lieu:"8 records de segments",km:10.2,m:{allure:"5:21/km",temps:"54:27"}},
    {d:"Jeu 27/08",past:1,k:"run",t:"Sortie vallonnée 10,8 km",lieu:"D+ 176 m · pic 176 bpm",km:10.8,m:{allure:"5:32/km",temps:"59:58",fc:147}},
    {d:"Ven 28/08",past:1,k:"run",t:"Sortie longue 13,4 km",lieu:"D+ 174 m",km:13.4,m:{allure:"5:56/km",temps:"1h20",fc:133}},
    {d:"Sam 29/08",past:1,k:"run",t:"Footing 7,9 km",lieu:"",km:7.9,m:{allure:"5:28/km",temps:"43:23"}}]},

{n:3, dates:"31 août – 6 septembre", du:"2026-08-31", tag:"En cours", type:"past", past:1,
 titre:"Retour à Paris",
 prevu:"25′ Z1 + 12×30″ Z5 · 25′ Z1 + 2×(3×2′ Z5) · 1h15-1h20 Z2 · 1h20-1h30 Z2 dont 15′ Z3",
 focus:"Reprise de l'intensité avec deux sorties progressives, et reprise du renforcement musculaire.",
 bilan:"Le retour au frais a fait bondir tes allures — 5:08/km le 31/08 avec un km à <b>4:12/km à 165 bpm</b>, ta meilleure référence de vitesse. Ton pic à <b>180 bpm</b> le 02/09 a permis de recalibrer les zones. Revers : tes footings sont passés de 6:00 à 5:26/km. <b>C'est précisément ce qu'on corrige dès la semaine 4.</b>",
 s:[{d:"Lun 31/08",past:1,k:"run",t:"Progressive 9,6 km",lieu:"Km 6 en 4:12, km 7 en 4:32",km:9.6,m:{allure:"5:08/km",temps:"49:08",fc:142,fcmax:175}},
    {d:"Mer 02/09",past:1,k:"run",t:"Progressive 9,0 km",lieu:"Km 5 en 4:34",km:9.0,m:{allure:"5:15/km",temps:"47:25",fc:146,fcmax:180}},
    {d:"Jeu 03/09",past:1,k:"strength",t:"Renfo salle 55′ + stepper 10′",lieu:"8 exercices machines"},
    {d:"Ven 04/09",past:1,k:"swim",t:"Natation 1 675 m",lieu:"35:58"},
    {d:"Ven 04/09",past:1,k:"run",t:"Footing 9,1 km",lieu:"",km:9.1,m:{allure:"5:28/km",temps:"49:41"}},
    {d:"Sam 05/09",past:1,k:"run",t:"Sortie longue 14,2 km",lieu:"17 records de segments 🔥",km:14.2,m:{allure:"5:26/km",temps:"1h17",fc:137}},
    {d:"Dim 06/09",k:"run",a:"sl_am",t:"1h20 à 1h30 Z2 dont 15′ Z3",km:15,f:[80,90],
     note:"Seule séance restante de la semaine. Teste ton allure cible 5:20/km : elle doit te sembler très confortable."}]},

{n:4, dates:"7 – 13 septembre", du:"2026-09-07", tag:"Charge · VO2max", type:"build",
 titre:"Entrée par l'intensité",
 focus:"Semaine <b>nettement durcie à ta demande</b> : on entre par le VO2max plutôt que par les accélérations. Deux séances de qualité et une sortie longue avec bloc à allure marathon. <b>Contrepartie non négociable : les footings de récupération doivent être VRAIMENT lents</b> (6:00-6:30/km). Tu ne peux pas monter l'intensité et garder des footings à 5:26.",
  planning:[{j:1},{j:2,i:[0]},{j:3,i:[1,2]},{j:4,i:[3]},{j:5,i:[4]},{j:6,i:[5]},{j:7,i:[6]}],
s:[{k:"run",a:"vo2max",t:"25′ Z1 + 4 × 4′ Z5, R 3′ Z1 + RC 10′ Z1",km:11,
     note:"🆕 Ta première vraie séance de VO2max. Vise 14,5 km/h sur tapis. Le piège absolu : partir trop vite sur la 1ʳᵉ. Elle doit te sembler presque facile."},
    {k:"strength",a:"renfo_a",t:"Renfo A — Force",lieu:"Leg press 210 · leg curl 60 · hip thrust 70 · abduction 95 · adduction 80 · mollets 61 · back ext. 10 · Pallof 20"},
    {k:"swim",a:"natation",t:"Natation endurance 2 000 m"},
    {k:"run",a:"cotes",t:"20′ Z1 + 5 Acc + 8 × côte 1′30 + RC 10′ Z1",km:11,
     note:"🆕 Sur tapis : 6-8 % d'inclinaison. C'est de la force pure, pas de la vitesse — ne cherche pas à aller vite en montée."},
    {k:"strength",a:"renfo_b",t:"Renfo B — Unilatéral",
     note:"Première fois : 2 séries au lieu de 3, bulgares sans haltères."},
    {k:"run",a:"endurance",t:"45′ Z1",km:8,f:[40,50],
     note:"Raccourci volontairement (1h → 45′) pour compenser l'intensité ajoutée cette semaine. Strictement en Z1."},
    {k:"run",a:"sl_am",t:"1h40 Z2 dont 20′ Z3",km:18,f:[95,105],
     note:"Première prise de contact avec l'allure marathon. Elle doit sembler facile — sinon tu as trop tapé en semaine."}]},

{n:5, dates:"14 – 20 septembre", du:"2026-09-14", tag:"Décharge · mariage", type:"taper",
 titre:"Semaine courte — mariage",
 focus:"🥂 Tu es <b>off du vendredi 18 au dimanche 20</b>. On en fait une vraie semaine de décharge : tout est condensé sur lundi-jeudi, <b>volume divisé par deux, intensité conservée</b>. C'est exactement le principe de l'affûtage — et ça tombe parfaitement après trois semaines de charge.",
  planning:[{j:1,i:[0]},{j:2,i:[1]},{j:3,i:[2]},{j:4,i:[3]},{j:"5–7",i:[4],lbl:"Coupure (mariage)"}],
s:[{k:"swim",a:"natation",t:"Natation récup 1 500 m",lieu:"Ou repos complet si les jambes sont lourdes"},
    {k:"run",a:"interval_1000",t:"25′ Z1 + 6 × 1000 m Z4, R 2′ Z1 + RC 10′ Z1",km:13,
     note:"🆕 Le format que tu voulais. 13,1 km/h sur tapis. 6 km de travail : c'est la seule vraie séance de la semaine, donne tout."},
    {k:"strength",a:"renfo_a",t:"Renfo A — Force",lieu:"Charges de la semaine 4, pas de montée"},
    {k:"run",a:"sl_am",t:"1h20 Z2 dont 15′ Z3",km:14,f:[75,85],
     note:"⚠️ Sortie longue avancée au jeudi, avant ton départ. Volontairement courte — la vraie progression reprend en semaine 6."},
    {k:"run",a:"off",t:"🥂 Mariage — coupure totale",fixe:"Vendredi 18 → dimanche 20 septembre",
     note:"Ne culpabilise pas et ne compense pas : cette coupure est planifiée. Trois jours de repos après trois semaines de charge, c'est une fenêtre de surcompensation. Tu reviendras plus fort lundi."}]},

{n:6, dates:"21 – 27 septembre", du:"2026-09-21", tag:"Charge · seuil", type:"build",
 titre:"Retour en charge — le seuil",
 focus:"Reprise franche après la coupure. Au menu : <b>ta séance de 4 × 2000 m</b> et le passage des <b>2 heures</b> en sortie longue — du jamais-fait cet été. La semaine la plus dense jusqu'ici.",
  planning:[{j:1},{j:2,i:[0]},{j:3,i:[1,2]},{j:4,i:[3]},{j:5,i:[4]},{j:6,i:[5]},{j:7,i:[6]}],
s:[{k:"run",a:"seuil_2000",t:"25′ Z1 + 4 × 2000 m Z4, R 2′ Z1 + RC 10′ Z1",km:15,
     note:"🆕 8 km cumulés au seuil, jambes fraîches après la coupure. 12,6 km/h sur tapis. Si le 4ᵉ bloc s'écroule, tu es parti trop vite."},
    {k:"strength",a:"renfo_a",t:"Renfo A — Force",lieu:"Reprise de la montée en charge"},
    {k:"swim",a:"natation",t:"Natation endurance 2 000 m"},
    {k:"run",a:"cotes",t:"25′ Z1 + 5 Acc + 12 × côte 1′30 + RC 10′ Z1",km:12,
     note:"🔬 Test FCmax : sur la dernière côte, monte à fond les 45 dernières secondes. Si ton pic dépasse 185 bpm, préviens-moi, on recalcule toutes les zones."},
    {k:"strength",a:"renfo_b",t:"Renfo B — Unilatéral",lieu:"Format complet : 3 séries, haltères"},
    {k:"run",a:"endurance",t:"45′ Z1",km:8,f:[40,50],
     note:"Récupération active avant la grosse sortie de dimanche."},
    {k:"run",a:"sl_am",t:"1h50 à 2h Z2 dont 30′ Z3",km:21,f:[110,120],
     note:"Première fois à allure marathon sur jambes fatiguées, et premier passage des 20 km. LA séance clé du mois."}]},

{n:7, dates:"28 septembre – 4 octobre", du:"2026-09-28", tag:"Charge + seuil", type:"build",
 titre:"Introduction du seuil",
 focus:"On <b>introduit le travail au seuil</b> — les blocs de 6′ en Z4 élèvent le plafond qui soutiendra ton allure marathon. Sortie longue légèrement rallongée pour préparer le semi en solo de la semaine prochaine.",
  planning:[{j:1},{j:2,i:[0]},{j:3,i:[1,2]},{j:4,i:[3]},{j:5,i:[4]},{j:6,i:[5]},{j:7,i:[6]}],
s:[{k:"run",a:"vma_court",t:"25′ Z1 + 12 × 40″ Z5, R 40″ Z1 + RC 10′ Z1",km:10},
    {k:"strength",a:"renfo_a",t:"Renfo A — Force",lieu:"Maintien des charges, plus de montée à partir d'ici"},
    {k:"swim",a:"natation",t:"Natation endurance 2 000 m"},
    {k:"run",a:"seuil",t:"25′ Z1 + 5 Acc + 5 × 6′ Z4, R 2′ Z1 + RC 10′ Z1",km:13,
     note:"Nouvelle séance pour toi. 30 min cumulées au seuil. Vise l'ennui sur le premier bloc."},
    {k:"strength",a:"renfo_b",t:"Renfo B — Unilatéral"},
    {k:"run",a:"endurance",t:"1h15 Z2",km:13,f:[70,80]},
    {k:"run",a:"sl_am",t:"2h10 à 2h15 Z2 dont 2 × 18′ Z3 (R 3′ Z2)",km:24,f:[125,135],
     note:"🥤 Première sortie avec ravitaillement complet. Teste la marque exacte du jour J."}]},

{n:8, dates:"5 – 11 octobre", du:"2026-10-05", tag:"Semi en solo", type:"race",
 titre:"Course test",
 focus:"⚠️ Le 20 km de Paris est complet — on remplace par un <b>semi-marathon en solo</b>, sur un parcours plat que tu choisis, avec tes affaires du jour J. Mini-affûtage en début de semaine pour arriver frais. Le chrono validera — ou ajustera — l'objectif 3h45.",
  planning:[{j:1},{j:2,i:[0]},{j:3,i:[1]},{j:4,i:[2]},{j:5},{j:6,i:[3]},{j:7,i:[4]}],
s:[{k:"run",a:"vma_court",t:"25′ Z1 + 2 × (6 × 40″ Z5, R 40″ Z1), R 2′ + RC 10′ Z1",km:9},
    {k:"strength",a:"renfo_a",t:"Renfo A — allégé (−30 %)",lieu:"Leg press 145 · hip thrust 50 · reste à 70 %"},
    {k:"run",a:"endurance",t:"55′ Z1",km:9,f:[50,60]},
    {k:"run",a:"acc",t:"30′ Z1 + 6 Acc + RC 5′ Z1",km:7},
    {k:"run",a:"course",t:"🏁 Semi-marathon en solo — 21,1 km",km:21.1,
     note:"Idéalement le week-end du 11 octobre (pile 4 semaines avant le marathon), sur un parcours plat, seul ou avec un lièvre. Sans peloton pour te tirer, vise 4:50-4:55/km soit 1h42-1h44. Pars 10 s/km trop lentement les 5 premiers km. Sous 1h42 valide 3h45 ; au-delà de 1h48 on ajuste vers 3h50-3h55."}]},

{n:9, dates:"12 – 18 octobre", du:"2026-10-12", tag:"Récup + relance", type:"build",
 titre:"Nouveau record de distance",
 focus:"Début de semaine en récupération, puis on relance fort avec une sortie longue à <b>27 km</b> — nouveau record, avant le pic de la semaine prochaine. Deux blocs de 20′ à allure marathon dedans.",
  planning:[{j:1,i:[0]},{j:2,i:[1]},{j:3,i:[2,3]},{j:4,i:[4]},{j:5},{j:6,i:[5]},{j:7,i:[6]}],
s:[{k:"run",a:"velo",t:"🚴 1h de vélo ou home trainer — récup"},
    {k:"run",a:"repos",t:"Repos ou 30′ Z1 très souple"},
    {k:"strength",a:"renfo_a",t:"Renfo A — Force",lieu:"On passe à 1 séance/semaine"},
    {k:"swim",a:"natation",t:"Natation récup 1 500 m"},
    {k:"run",a:"vma_court",t:"25′ Z1 + 12 × 40″ Z5, R 40″ Z1 + RC 10′ Z1",km:10},
    {k:"run",a:"endurance",t:"1h20 Z2",km:14,f:[75,85]},
    {k:"run",a:"sl_am",t:"2h25 à 2h35 Z2 dont 2 × 20′ Z3 (R 3′ Z2)",km:27,f:[145,155],
     note:"Tu vas dépasser ton record de distance. Le 2ᵉ bloc Z3 le plus tard possible, après 1h30."}]},

{n:10, dates:"19 – 25 octobre", du:"2026-10-19", tag:"Pic de charge · 30 km", type:"peak",
 titre:"La semaine décisive",
 focus:"<b>Le sommet du plan : 30 km en sortie longue</b>, ta plus grosse distance jusqu'au marathon lui-même. On la fait courir seule, sans vélo derrière — à cette distance, la fatigue du km 35 est déjà largement travaillée. Plus 4 × 8′ au seuil. Si tu passes cette semaine, le marathon est joué.",
  planning:[{j:1},{j:2,i:[0]},{j:3,i:[1,2]},{j:4,i:[3]},{j:5},{j:6,i:[4]},{j:7,i:[5]}],
s:[{k:"run",a:"vma_court",t:"25′ Z1 + 2 × (8 × 40″ Z5, R 40″ Z1), R 2′ + RC 10′ Z1",km:11},
    {k:"strength",a:"renfo_a",t:"Renfo A — Force"},
    {k:"swim",a:"natation",t:"Natation récup 1 500 m"},
    {k:"run",a:"seuil",t:"25′ Z1 + 5 Acc + 4 × 8′ Z4, R 2′ Z1 + RC 10′ Z1",km:14},
    {k:"run",a:"endurance",t:"1h25 Z2",km:15,f:[80,90]},
    {k:"run",a:"sl_am",t:"2h45 à 2h55 Z2 dont 45′ Z3",km:30,f:[160,180],
     note:"🔑 La plus grosse séance du plan, tout court. Ravitaillement en conditions réelles. Si tu es encore frais à l'arrivée, 20-30′ de vélo très souple en bonus — jamais obligatoire."}]},

{n:11, dates:"26 octobre – 1ᵉʳ novembre", du:"2026-10-26", tag:"Début affûtage", type:"taper",
 titre:"On coupe le volume, on garde l'intensité",
 focus:"Les <b>3 × 12′ au seuil</b> sont la dernière séance dure du bloc. Après, tout est en récupération. Sortie longue ramenée à 18 km — une baisse de 40 % par rapport au pic, ce qui est normal et voulu en plein affûtage.",
  planning:[{j:1},{j:2,i:[0]},{j:3,i:[1,2]},{j:4,i:[3]},{j:5,i:[4]},{j:6},{j:7,i:[5]}],
s:[{k:"run",a:"vma_court",t:"25′ Z1 + 2 × (8 × 45″ Z5, R 45″ Z1), R 2′ + RC 10′ Z1",km:11},
    {k:"strength",a:"renfo_a",t:"Renfo A — allégé, dernière séance du bloc",lieu:"Charges à 70 %"},
    {k:"swim",a:"natation",t:"Natation récup 1 500 m"},
    {k:"run",a:"endurance",t:"1h15 Z2",km:13,f:[70,80]},
    {k:"run",a:"seuil",t:"25′ Z1 + 5 Acc + 3 × 12′ Z4, R 3′ Z1 + RC 10′ Z1",km:15,
     note:"36 min au seuil : la plus grosse séance de qualité du plan."},
    {k:"run",a:"sl",t:"1h40 Z2",km:18,f:[95,105],
     note:"Sortie longue volontairement raccourcie (−40 % par rapport au pic de 30 km). Tu vas te sentir en manque — c'est le signe que l'affûtage marche. N'ajoute rien."}]},

{n:12, dates:"2 – 8 novembre", du:"2026-11-02", tag:"🏁 Semaine du marathon", type:"taper",
 titre:"Ne rien gagner, ne rien perdre",
 focus:"<b>Zéro renfo, zéro natation, zéro nouveauté.</b> Ton travail est fait : il ne reste qu'à arriver frais sur la Promenade des Anglais.",
  planning:[{j:1},{j:2,i:[0]},{j:3},{j:4,i:[1]},{j:5},{j:6,i:[2]},{j:7,i:[3]}],
s:[{k:"run",a:"vma_court",t:"25′ Z1 + 8 × 40″ Z5, R 40″ Z1 + RC 10′ Z1",km:8,
     note:"Entretien nerveux, sans fatigue."},
    {k:"run",a:"endurance",t:"30′ Z1",km:5},
    {k:"run",a:"acc",t:"20 à 25′ Z1 + 3 Acc",km:4,f:[20,25],lieu:"Prépare ton sac le soir"},
    {k:"run",a:"course",t:"🏁 MARATHON NICE – CANNES",fixe:"Dimanche 8 novembre, 8h00",km:42.2,
     note:"5:30/km jusqu'au km 5. Gel toutes les 35 min dès le km 8. FC sous 163 au km 25. Et tu doubles tout le monde après le km 32. 🔱"}]}
];
